### ISSUE TITLE
An unhandled exception occurred: Cannot find module '@angular-devkit/build-angular/package.json

### ISSUE THREAD

**Issue by brykurt** [93Alliance/ng-chartjs#14]
I couldn't run the project and it cannot find the module

 '@angular-devkit/build-angular/package.json

**Comment by 93Alliance** [comment]
Please show the results of the `npm i` command.

**Comment by 93Alliance** [comment]
This is mine.

```
vincent@Inspiron-7559 Dir:~/project/github/ng-chartjs → develop
·····$npm i
npm WARN @angular-devkit/build-ng-packagr@0.900.6 requires a peer of tsickle@~0.37.1 || ~0.38.0 but none is installed. You must install peer dependencies yourself.
npm WARN sass-loader@8.0.0 requires a peer of node-sass@^4.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN sass-loader@8.0.0 requires a peer of fibers@>= 3.1.0 but none is installed. You must install peer dependencies yourself.
npm WARN webpack-subresource-integrity@1.3.4 requires a peer of html-webpack-plugin@^2.21.0 || ~3 || >=4.0.0-alpha.2 <5 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.2 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.11 (node_modules/webpack-dev-server/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.11: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.11 (node_modules/watchpack/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.11: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.11 (node_modules/karma/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.11: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

audited 18472 packages in 10.075s
found 89 vulnerabilities (61 low, 2 moderate, 25 high, 1 critical)
  run `npm audit fix` to fix them, or `npm audit` for details
```

**Comment by brykurt** [comment]
Here's the result:

PS D:\ncovid\ng-chartjs> npm i command
npm WARN tarball tarball data for typescript@3.6.4 (sha1-sYdSuzeSvBoCgTNff26/G7/FuR0=) seems to be corrupted. Trying one more time.
npm WARN tar ENOENT: no such file or directory, open 'D:\ncovid\ng-chartjs\node_modules\.staging\@angular\material-071ce962\bundles\material.umd.js.map'
npm WARN tar ENOENT: no such file or directory, open 'D:\ncovid\ng-chartjs\node_modules\.staging\@angular\material-071ce962\bundles\material.umd.min.js.map'
npm WARN tarball tarball data for typescript@3.7.5 (sha1-BpLiH2X9QQi5MwI4qsEd0uF3oa4=) seems to be corrupted. Trying one more time.
npm WARN tar ENOENT: no such file or directory, open 'D:\ncovid\ng-chartjs\node_modules\.staging\@angular\material-071ce962\fesm2015\progress-bar.js.map'
npm WARN tar ENOENT: no such file or directory, open 'D:\ncovid\ng-chartjs\node_modules\.staging\@angular\material-071ce962\fesm2015\progress-spinner.js.map'
npm WARN tar ENOENT: no such file or directory, open 'D:\ncovid\ng-chartjs\node_modules\.staging\@angular\material-071ce962\fesm2015\radio.js.map'
npm WARN tar ENOENT: no such file or directory, open 'D:\ncovid\ng-chartjs\node_modules\.staging\@angular\core-1531db6b\fesm2015\testing.js.map'
npm ERR! code EPERM
npm ERR! syscall unlink
npm ERR! path D:\ncovid\ng-chartjs\node_modules\.staging\typescript-d446fe9e\lib\typescriptServices.js
npm ERR! errno -4048
npm ERR! Error: EPERM: operation not permitted, unlink 'D:\ncovid\ng-chartjs\node_modules\.staging\typescript-d446fe9e\lib\typescriptServices.js'
npm ERR!  [OperationalError: EPERM: operation not permitted, unlink 'D:\ncovid\ng-chartjs\node_modules\.staging\typescript-d446fe9e\lib\typescriptServices.js'] {
npm ERR!   cause: [Error: EPERM: operation not permitted, unlink 'D:\ncovid\ng-chartjs\node_modules\.staging\typescript-d446fe9e\lib\typescriptServices.js'] {
npm ERR!     errno: -4048,
npm ERR!     code: 'EPERM',
npm ERR!     syscall: 'unlink',
npm ERR!     path: 'D:\\ncovid\\ng-chartjs\\node_modules\\.staging\\typescript-d446fe9e\\lib\\typescriptServices.js'
npm ERR!   },
npm ERR!   stack: "Error: EPERM: operation not permitted, unlink 'D:\\ncovid\\ng-chartjs\\node_modules\\.staging\\typescript-d446fe9e\\lib\\typescriptServices.js'",
npm ERR!   errno: -4048,
npm ERR!   code: 'EPERM',
npm ERR!   syscall: 'unlink',
npm ERR!   path: 'D:\\ncovid\\ng-chartjs\\node_modules\\.staging\\typescript-d446fe9e\\lib\\typescriptServices.js',
npm ERR!   parent: '@angular-devkit/build-optimizer'
npm ERR! }
npm ERR!
npm ERR! The operation was rejected by your operating system.
npm ERR! It's possible that the file was already in use (by a text editor or antivirus),   
npm ERR! or that you lack permissions to access it.
npm ERR!
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator.

**Comment by 93Alliance** [comment]
You need to upgrade your Angular/cli .

```
npm uninstall -g @angular/cli
npm cache clean --force
npm install -g @angular/cli
```
Here's my env

```
·····$ng version

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 9.0.5
Node: 10.15.0
OS: linux x64

Angular: 
... 
Ivy Workspace: 

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.900.5
@angular-devkit/core         9.0.5
@angular-devkit/schematics   9.0.5
@schematics/angular          9.0.5
@schematics/update           0.900.5
rxjs                         6.5.4
```

**Comment by brykurt** [comment]
Okay, I'll follow that, hold on. Thanks!
