### ISSUE TITLE
Differences to ng2-charts

### ISSUE THREAD

**Issue by fuerst** [93Alliance/ng-chartjs#16]
Hi, thank you for your work! I'm unsure which package to use: ng2-charts or ng-chartjs. What was your motivation to create ng-chartjs and which advantages do I get when using it instead of ng2-charts?

**Comment by 93Alliance** [comment]
ng-chartjs came about because ng2-charts was unmaintained and it had some bugs and issues.

Advantages of ng-chartjs are lightweight and inline plugins, global plugins, ngZone optimization

**Comment by 93Alliance** [comment]
You can choose any of them, this one is in use in my project, so I'll do my best to maintain it.

**Comment by fuerst** [comment]
Thanks a lot, I'll give it a try.
