### ISSUE TITLE
chartclick for line-chart

### ISSUE THREAD

**Issue by bvandenbon** [93Alliance/ng-chartjs#2]
Am I correct that the `(chartclick)` event is not supported for the line-charts ?
I can't get it to work.

**Comment by 93Alliance** [comment]
Sorry for my late reply, I have tested it, chartClick, this event is valid, chartHover, this event cannot be used normally, but I have fixed it.

You need to update 0.0.8 version.

example:

html file
```
  <canvas *ngIf="true" ngChartjs [datasets]="lineChartData" [labels]="lineChartLabels"
    [options]="lineChartOptions" [colors]="lineChartColors" [legend]="lineChartLegend"
    [chartType]="lineChartType"
    (chartHover)="chartHovered($event)" (chartClick)="chartClicked($event)"></canvas>
```
typescript file

```
  // events
  chartClicked(e: any): void {
    console.log('click', e);
  }

  chartHovered(e: any): void {
    console.log('hover', e);
  }
```
You can also watch this demo. [link](https://github.com/93Alliance/ng-chartjs/tree/master/src/app/line-chart)

Thank you for the question!

**Comment by bvandenbon** [comment]
Thank you for your feedback. This is certainly helpful !
I will try this, later this evening. (looking forward to it)

Op do 10 jan. 2019 om 16:23 schreef Vincent <notifications@github.com>:

**Comment by bvandenbon** [comment]
Just wanted to let you know that it works ! :) 
Thanks you very much. 👍
