### ISSUE TITLE
Pie chart having groupped labels with values

### ISSUE THREAD

**Issue by ursedaniel** [93Alliance/ng-chartjs#21]
Hello, I want to have the pie chart values groupped, i see that I can do that with Labels, but for the values I can't have an array of values, do you guys know a way to achieve this?
As you can see in the photo only the first label has the corresponding value, but the 2nd one doesnt.
Thanx!
<img width="671" alt="Screenshot 2020-08-02 at 16 10 11" src="https://user-images.githubusercontent.com/17604236/89124080-e5b59e00-d4dc-11ea-927e-e88b4229be7f.png">
<img width="425" alt="Screenshot 2020-08-02 at 16 12 33" src="https://user-images.githubusercontent.com/17604236/89124082-e817f800-d4dc-11ea-8b9a-42d2b75fba0d.png">

**Comment by 93Alliance** [comment]
You can't use pie chart with your dataset. You could try bar chart.
```
[[300,15],500,100]
```
Because in pie chart, chart.js need to calculate the scale, `[300, 15]` can't be calculated with other values in the array.

**Comment by 93Alliance** [comment]
You can try it. 
https://stackblitz.com/edit/angular-ngchartjs-issues21

**Comment by ursedaniel** [comment]
@93Alliance worked like a charm, thank you so much!

**Comment by ursedaniel** [comment]
I'm facing a problem, when running with --prod flag I get this error in console after following your example @93Alliance : 
![Screenshot 2020-10-18 at 17 49 21](https://user-images.githubusercontent.com/17604236/96371401-419dd380-116a-11eb-8bbd-24cac98a38a4.png)
<img width="517" alt="Screenshot 2020-10-18 at 17 49 39" src="https://user-images.githubusercontent.com/17604236/96371411-4cf0ff00-116a-11eb-9c71-75755030aa67.png">
<img width="561" alt="Screenshot 2020-10-18 at 17 49 58" src="https://user-images.githubusercontent.com/17604236/96371430-58dcc100-116a-11eb-88e9-54b6ebe9e7c5.png">
Any ideas how to fix it? without --prod flag it works pretty good but I need it to be prod valid, thanks!
