### ISSUE TITLE
Show anotations that are in different time range than the chart 

### ISSUE THREAD

**Issue by patolax** [93Alliance/ng-chartjs#22]
[Question]
I have a case where annotations and chart data are on different time ranges.

annotations [10.30AM, 4.45PM, 6.15PM, 8PM] // few events scattered 
    
chart Data [11Am, 12PM, 1PM ........., 7PM] // every hour

If I plot these on the same chart with X axis with time unit hour and labels generated from 10.30 PM to 8PM, the line chart would be totally misaligned.
Is there a way to plot them correctly in a single chart?

**Comment by 93Alliance** [comment]
Could you provide the code for your experiment?

**Comment by patolax** [comment]
Please see the sample I created below
https://stackblitz.com/edit/angular-n9tm48
chart data
11:00  12:00  13:00   15:00   16:00 
65,       59,        80,     55,        70

annotations
10.30    14.30
ON         OFF

As you can see the chart data suppose to be at 16.00 is now plotted at 14:00.  Chart data is misaligned.

**Comment by 93Alliance** [comment]
The date is wrong

```
        {
          drawTime: 'afterDraw',
          type: 'line',
          mode: 'vertical',
          scaleID: 'x-axis-0',
          value: new Date(2020, 8, 1, 14.30 ,0 ,0),
          borderColor: 'rgba(175,72, 32,1)',
          borderWidth: 2,
          borderDash: [10, 10],
          borderDashOffset: 5,
          label: {
            backgroundColor: 'rgba(175,72, 32,1)',
            content: 'OFF',
            enabled: true,
            position: 'bottom',
          }
        },
```

`new Date(2020, 8, 1, 14.30 ,0 ,0),` => `new Date(2020, 8, 1, 14, 30 ,0 )`

**Comment by patolax** [comment]
sorry, I have fixed it. But that's not the problem.  Chart data getting misaligned is the major issue. How do we plot two different ranges on the same chart.

**Comment by 93Alliance** [comment]
First, your data and tags don't correspond.
```
data: [65, 59, 80, 55, 70],

  lineChartLabels: Array<any> = [
    new Date(2020, 8, 1, 10 , 30 ,0), 
    new Date(2020, 8, 1, 11 ,0 ,0), 
    new Date(2020, 8, 1, 12 ,0 ,0), 
    new Date(2020, 8, 1, 13 ,0 ,0), 
    new Date(2020, 8, 1, 14 ,30 ,0), 
    new Date(2020, 8, 1, 15 ,0 ,0), 
    new Date(2020, 8, 1, 16 ,0 ,0), ];
```
In general, you should delete 10.30 and 14.30. If you want to keep them, you should customize label callback function.

**Comment by 93Alliance** [comment]
```
  lineChartLabels: Array<any> = [
    // new Date(2020, 8, 1, 10 , 30 ,0),
    new Date(2020, 8, 1, 11, 0, 0),
    new Date(2020, 8, 1, 12, 0, 0),
    new Date(2020, 8, 1, 13, 0, 0),
    // new Date(2020, 8, 1, 14.30 ,0 ,0),
    new Date(2020, 8, 1, 15, 0, 0),
    new Date(2020, 8, 1, 16, 0, 0)
  ];
```

```
  start = new Date(2020, 8, 1, 10 , 0 ,0) // -offset;
  end = new Date(2020, 8, 1, 16, 30, 0 ,0) // +offset;
```

```
    scales: {
      xAxes: [
        {
          type: "time",
          distribution: "linear",
          time: {
            unit: "hour",
            min: this.start,
            max: this.end
          }
        }
      ],
```

**Comment by patolax** [comment]
awsome! thanks a lot
