### ISSUE TITLE
Stacked Bar Chart background colors 

### ISSUE THREAD

**Issue by patolax** [93Alliance/ng-chartjs#23]
I am trying to change the background color of the stacked bar chart. But it does not apply.

https://stackblitz.com/edit/angular-8qvt2f?file=src%2Fapp%2Fapp.component.ts

**Comment by 93Alliance** [comment]
You may use `colors` property. 
demo https://stackblitz.com/edit/angular-ng-chartjs-issue23?file=src/app/app.component.html

**Comment by patolax** [comment]
I think there is something wrong with your demo
https://stackblitz.com/edit/angular-ng-chartjs-issue23?file=src/app/app.component.html
see the _acked_ and _closed_ colors are not configured. They are gray. 
What color property has done is configuring the _new_ with different colors, which is wrong.

**Comment by patolax** [comment]
Ok, colors array has to be something like this. an Item for each stacked category. This is a bit too inefficient and large. But it works, Original chartjs configuration is much simpler. 

public colors = [
    {
      backgroundColor: [
         'rgba(255, 99, 132, 0.2)',
         'rgba(255, 99, 132, 0.2)',
        'rgba(255, 99, 132, 0.2)',
        'rgba(255, 99, 132, 0.2)',
        'rgba(255, 99, 132, 0.2)',
         'rgba(255, 99, 132, 0.2)',
         'rgba(255, 99, 132, 0.2)',
      ],
    },
    {
      backgroundColor: [
       'rgba(153, 102, 255, 0.2)',
        'rgba(153, 102, 255, 0.2)',
        'rgba(255, 206, 86, 0.2)',
        'rgba(75, 192, 192, 0.2)',
        'rgba(153, 102, 255, 0.2)',
        'rgba(255, 159, 64, 0.2)',
        'rgba(23, 34, 200, 0.2)',
      ],
    }
  ];

**Comment by 93Alliance** [comment]
You may use it by this way.

```
  public colors = [
    {
      backgroundColor: 'rgb(75, 192, 192)',
    },
    {
      backgroundColor: 'rgb(132, 99, 132)',
    },
    {
      backgroundColor: 'rgb(201, 203, 207)',
    }
  ];
```

https://stackblitz.com/edit/angular-ng-chartjs-issue23?file=src/app/app.component.ts
