### ISSUE TITLE
Chart annotations not visible on Production bulid but works fine in development 

### ISSUE THREAD

**Issue by patolax** [93Alliance/ng-chartjs#25]
The image below shows how annotations are rendered on angular deployment on IIS (yarn build:prod) and development (yarn start/ng serve). In the former case, annotations are not visible but in the development cases, they are visible. 

How to solve this?

![image](https://user-images.githubusercontent.com/29444156/94108742-30231d80-fe83-11ea-92b9-10e20b876fe1.png)

I also tried following with no luck.
https://stackoverflow.com/questions/56706507/chart-js-line-from-annotations-plugin-is-not-appearing

I am using angular 7, following libs
```
 
    "chart.js": "2.7.3",
    "ng-chartjs": "0.0.9",
    "chartjs-plugin-annotation": "0.5.7"
  },
  "devDependencies": {
    "ts-node": "^8.6.2",
    "tslint": "~5.11.0",
    "typescript": "3.1.6",
    "@types/chart.js": "2.7.42"
  }
```

**Comment by 93Alliance** [comment]
That's my understanding.

The annotations plugin doesn't work when you build a project by using build:prod!

**Comment by patolax** [comment]
How do we build then to include annotations for deployment?

**Comment by 93Alliance** [comment]
I tried to deploy it, but it worked.

**Comment by 93Alliance** [comment]
You can clone the project and then switch versions.

```
git checkout b534dae
```
change ng-chartjs version
```
"ng-chartjs": "0.0.9",
```
build
```
npm run release
```
you can run project by http-server

**Comment by patolax** [comment]
could it be the versions I use? I tried local IIS and Azure deployment. Both showed the same issue. 
So the only conclusion is yarn build:prod breaks it. Any ideas on how to debug this?

I ll also try your sample later.

**Comment by 93Alliance** [comment]
Can you provide me with a demo?

**Comment by patolax** [comment]
I ll try. Were you able to get it to work with build:prod

**Comment by 93Alliance** [comment]
My email onlyliveworld@gmail.com

**Comment by patolax** [comment]
In this repo I was able to precisely recreate the issue I am facing.
https://github.com/patolax/chart-app

Steps
1. Do yarn start (annotations should be visible)
2. Do yarn build: prod and deploy the dist folder on IIS. (annotations are not visible)

**Comment by 93Alliance** [comment]
I can't see anything. You can try to upgrade the project

**Comment by patolax** [comment]
Sorry, I have updated it to a public repo now.

**Comment by 93Alliance** [comment]
You try to update chart.js version to 2.9.3.

```
"chart.js": "2.9.3",
```

**Comment by patolax** [comment]
awsome! that worked. I was not sure which version was compatible with Angular 7.
