### ISSUE TITLE
 Cannot use namespace 'Chart' as a type error

### ISSUE THREAD

**Issue by patolax** [93Alliance/ng-chartjs#29]
I moved my project to angular 11. Then upgraded the modules to following versions.
    

    "chart.js": "2.9.4",
    "chartjs-plugin-annotation": "0.5.7",
    "ng-chartjs": "0.2.1"
    "@types/chart.js": "2.9.31",

I end up getting this error.  I also tried using all most recent versions of each modules but error does not go away. How can we move Forward. 

```
node_modules/ng-chartjs/node_modules/chart.js/types/index.esm"' has no exported member 'ChartDataSets'.

18     datasets: Chart.ChartDataSets[];
                       ~~~~~~~~~~~~~


Error: node_modules/ng-chartjs/lib/ng-chartjs.directive.d.ts:37:12 - error TS2709: Cannot use namespace 'Chart' as a type.

37     chart: Chart;
              ~~~~~
```

If I use old versions we use in angular 7 after upgrading to angular 11, we get following error
    "ng-chartjs": "0.0.9",
    "chart.js": "2.9.3",
    "@types/chart.js": "2.7.42",

R3InjectorError(DashboardModule)[NgChartjsService -> InjectionToken [ngx-chart-js] Global Custom Plugin -> InjectionToken [ngx-chart-js] Global Custom Plugin -> InjectionToken [ngx-chart-js] Global Custom Plugin -> InjectionToken [ngx-chart-js] Global Custom Plugin]: 
  NullInjectorError: No provider for InjectionToken [ngx-chart-js] Global Custom Plugin!

**Comment by 93Alliance** [comment]
Later I will update ng-chartjs to Angular 11.

**Comment by duongleh** [comment]
@93Alliance please upgrade to Angular 11 as soon as possible. I really need it in my project.

**Comment by 93Alliance** [comment]
The ng-chartjs has been updated to Angular 11!

**Comment by duongleh** [comment]
@93Alliance the issues still persists

**Comment by 93Alliance** [comment]
"chart.js": "2.9.4",
"chartjs-plugin-annotation": "0.5.7",
"ng-chartjs": "0.2.2"
"@types/chart.js": "2.9.31",

What is error?

**Comment by 93Alliance** [comment]
You can look at the ng-chartjs repository code.

**Comment by duongleh** [comment]
![image](https://user-images.githubusercontent.com/28813618/118000564-1f6edb80-b370-11eb-91fe-638e0a6136a1.png)
![image](https://user-images.githubusercontent.com/28813618/118000635-33b2d880-b370-11eb-9e58-e751e41d76a6.png)
@93Alliance the problem is the same as in the original description

**Comment by 93Alliance** [comment]
[ngx-lite-chartjs.tar.gz](https://github.com/93Alliance/ng-chartjs/files/6467292/ngx-lite-chartjs.tar.gz)

Please try this project. I'm ok!

**Comment by ganesh-vellanki** [comment]
Hi @93Alliance I am able to install latest 0.2.2 & run existing project without any issues, thanks for the update! I have a question though, Are you planning on releasing new version to support chartjs 3.*.* ?

**Comment by ganesh-vellanki** [comment]
Hi @duong-le , I recommend to try deleting all node_modules & re-install, sometimes this method works for me.
my pkgs are
```
"@types/chart.js": "2.9.32",
"chart.js": "~2.9.4",
"ng-chartjs": "~0.2.2",
```

**Comment by duongleh** [comment]
@ganesh-vellanki thanks for your suggestion. I did remove `node_modules` and did a fresh installation. I think I'm gonna try it one more time later and give feedback.

**Comment by 93Alliance** [comment]
> Hi @93Alliance I am able to install latest 0.2.2 & run existing project without any issues, thanks for the update! I have a question though, Are you planning on releasing new version to support chartjs 3._._ ?

The next version will support chart.js 3.

**Comment by patolax** [comment]
@93Alliance 

![image](https://user-images.githubusercontent.com/29444156/143970093-3bbf2c88-0f1f-4e28-9d6e-974e0dde3090.png)


I am still getting these error when I tried 

```
"@angular/core": "^11.2.14",
"chart.js": "3.6.0",
"chartjs-plugin-annotation": "1.1.0",
"ng-chartjs": "0.2.3",
"@types/chart.js": "2.9.34",
```

I also tried "chart.js": "3.2.1",
but still the same error.

Any idea what I am doing wrong.

**Comment by 93Alliance** [comment]
> @93Alliance
> 
> ![image](https://user-images.githubusercontent.com/29444156/143970093-3bbf2c88-0f1f-4e28-9d6e-974e0dde3090.png)
> 
> I am still getting these error when I tried
> 
> ```
> "@angular/core": "^11.2.14",
> "chart.js": "3.6.0",
> "chartjs-plugin-annotation": "1.1.0",
> "ng-chartjs": "0.2.3",
> "@types/chart.js": "2.9.34",
> ```
> 
> I also tried "chart.js": "3.2.1", but still the same error.
> 
> Any idea what I am doing wrong.

![image](https://user-images.githubusercontent.com/33192459/143970525-984e0d63-62c0-4e4f-9f5f-9127d3ca6509.png)

Chart.js 3.0 is not currently supported.

**Comment by timon0305** [comment]
ng-chartjs is not working on Angular v10. They say there is missing dependencies.

**Comment by timon0305** [comment]
<img width="1356" alt="Screen Shot 2022-03-18 at 7 04 09 PM" src="https://user-images.githubusercontent.com/59460476/158991880-e2d6c637-b1e1-453f-969b-604a20479405.png">

**Comment by 93Alliance** [comment]
First I suggest you use Angular 11. Currently ng-Chartjs does not match Angular 10. I will release a special version for Angular10 in my spare time.
