### ISSUE TITLE
After moving to angular 14.3.0, ng-chartjs@0.2.5 is not working properly

### ISSUE THREAD

**Issue by patolax** [93Alliance/ng-chartjs#36]
we moved from ng 12 to 14. Now the certain features of the ng-chartjs is not working. Will there be a new version?

**Comment by 93Alliance** [comment]
You should be able to use version 0.2.5 for angular 14. If there is any problem, you can let me know.

**Comment by patolax** [comment]
I had to fix some chartjs v3-related changes and install chartjs-adapter-date-fns to resolve some of the major issues.
