### ISSUE TITLE
@angular/core has not export member InjectionToken

### ISSUE THREAD

**Issue by radici** [93Alliance/ng-chartjs#5]
hi i have the following error inside the file:
plugin-token.d.ts:

import { InjectionToken } from '@angular/core';

'@angular/core has not export member InjectionToken'
Thanks

**Comment by 93Alliance** [comment]
What is your angular version?

**Comment by 93Alliance** [comment]
example

install ng-chartjs
```
npm install --save ng-chartjs@latest
```

import lib to project

```
import { NgChartjsModule } from 'ng-chartjs';
@NgModule({
    NgChartjsModule
})
```

**Comment by 93Alliance** [comment]
Please reply me after the test. Thank you

**Comment by 93Alliance** [comment]
Has the problem been solved？
