### ISSUE TITLE
Changing chart type on the fly doesn't work (for me)

### ISSUE THREAD

**Issue by T0BiD** [93Alliance/ng-chartjs#6]
HI 93Alliance,
thanks for continuing to maintain this btw

I do have a problem with updating the chartType when pressing a button.

This is my chart:
```
<div style="width: 1000px; text-align: center; margin-top:20px">
  <canvas id="chart" ngChartjs [datasets]="chartData" [labels]="chartLabels" [options]="chartOptions"
    [legend]="chartLegend" [chartType]="chartType">
  </canvas>
</div>
```

And this is what I do to update the chart:

```
this.chartType = 'bar';
this.chartData = [
    {
        label: 'name',
        data: [1, 2, 3]
}];
this.chartLabels = ['newlabel1', 'newlabel2', 'newlabel3'];
```
Now, the values and the labels update, but the type of the chart doesnt change.

Appreciate your help,
-T0Bi

**Comment by 93Alliance** [comment]
Thank you for your issue.

First, the current 0.0.9 version of ng-chartjs does not support changing chart type.

I just updated the ng-chartjs library to version 0.1.0,and have added this feature. You can try it.

```
npm i ng-chartjs@latest --save
```
You can view the [demo](https://93alliance.github.io/ng-chartjs/) and [source](https://github.com/93Alliance/ng-chartjs/tree/master/src/app/chart-type) code

**Comment by 93Alliance** [comment]
Please reply me after the test. Thank you

**Comment by T0BiD** [comment]
@93Alliance worked like a charm after updating 👍
